const pages = Array.from({length:20}, (_,i)=>`pages/page-${String(i+1).padStart(2,'0')}.png`);
const qrMap = window.QR_MAP || {};
const spreads = [{cover: pages[0]}];
for (let i = 1; i < pages.length; i += 2) spreads.push({left: pages[i], right: pages[i+1] || null, pageLeft: i+1, pageRight: (i+2 <= pages.length ? i+2 : null)});
let spreadIndex = 0, turning = null;
const book = document.getElementById('book'), pageInfo = document.getElementById('pageInfo'), prevBtn = document.getElementById('prevBtn'), nextBtn = document.getElementById('nextBtn'), zoomRange = document.getElementById('zoomRange'), zoomLabel = document.getElementById('zoomLabel'), stage = document.getElementById('stage'), toast = document.getElementById('toast');
function toastMsg(){toast.classList.add('show');clearTimeout(window._t);window._t=setTimeout(()=>toast.classList.remove('show'),1200)}
function qrHtml(pageNum){const items = qrMap[String(pageNum)] || [];return items.map((q,idx)=>`<a class="qr-link" href="${q.url}" target="_blank" rel="noopener" aria-label="QR ${idx+1}" style="left:${q.x}%;top:${q.y}%;width:${q.w}%;height:${q.h}%;"></a>`).join('')}
function pageLayer(pageNum, src){return `<div class="page-layer"><img src="${src}" alt="page ${pageNum || ''}">${pageNum ? qrHtml(pageNum) : ''}</div>`}
function blankLayer(){return `<div class="page-layer"><div style="width:100%;height:100%;background:linear-gradient(180deg,#fbfbfb,#f0f0f0)"></div></div>`}
function pageHtml(pageNum, src){return src ? pageLayer(pageNum, src) : blankLayer()}
function staticPage(cls, pageNum, src){return `<div class="page-static ${cls}">${pageHtml(pageNum, src)}</div>`}
function updateControls(){prevBtn.disabled = spreadIndex===0 || !!turning; nextBtn.disabled = spreadIndex===spreads.length-1 || !!turning; if (spreadIndex===0) pageInfo.textContent = `1 / ${pages.length} бет · Мұқаба`; else { const s = spreads[spreadIndex]; pageInfo.textContent = s.pageRight ? `${s.pageLeft}–${s.pageRight} / ${pages.length} бет` : `${s.pageLeft} / ${pages.length} бет`; }}
function render(){const s = spreads[spreadIndex]; let html=''; if (spreadIndex===0){ html += `<div class="page-static cover">${pageHtml(1,s.cover)}</div>`; if (spreads.length>1) html += `<div class="edge-hint right" data-dir="next"></div>`; } else { html += staticPage('left', s.pageLeft, s.left); html += staticPage('right', s.pageRight, s.right); html += `<div class="gutter"></div>`; if (spreadIndex>0) html += `<div class="edge-hint left" data-dir="prev"></div>`; if (spreadIndex<spreads.length-1) html += `<div class="edge-hint right" data-dir="next"></div>`; } book.innerHTML = html; wireEdges(); wireQr(); updateControls(); }
function wireQr(){book.querySelectorAll('.qr-link').forEach(a=>{a.addEventListener('pointerdown',e=>e.stopPropagation());a.addEventListener('click',e=>{e.stopPropagation();toastMsg()})})}
function wireEdges(){book.querySelectorAll('.edge-hint').forEach(edge=>{edge.addEventListener('pointerdown',startDrag);edge.addEventListener('click',e=>e.preventDefault())})}
function setupTurnScene(dir){const curr=spreads[spreadIndex]; if (dir==='next'){const next=spreads[spreadIndex+1]; if (spreadIndex===0){book.innerHTML = `<div class="page-static left">${pageHtml(next.pageLeft,next.left)}</div><div class="page-static right">${pageHtml(next.pageRight,next.right)}</div><div class="gutter"></div><div class="turn-page forward" id="turner"><div class="face front">${pageHtml(1,spreads[0].cover)}</div><div class="face back">${pageHtml(next.pageLeft,next.left)}</div></div>`; const t=document.getElementById('turner'); t.style.left='25%'; t.style.width='50%';} else {const nextLeft = next.left || null; book.innerHTML = `${staticPage('left', curr.pageLeft, curr.left)}${staticPage('right', next.pageRight, next.right)}<div class="gutter"></div><div class="turn-page forward" id="turner"><div class="face front">${pageHtml(curr.pageRight,curr.right)}</div><div class="face back">${pageHtml(nextLeft?next.pageLeft:null,nextLeft)}</div></div>`;} } else {const prev=spreads[spreadIndex-1]; if (spreadIndex===1){book.innerHTML = `<div class="page-static cover">${pageHtml(1,pages[0])}</div><div class="turn-page backward" id="turner"><div class="face front">${pageHtml(curr.pageLeft,curr.left)}</div><div class="face back">${pageHtml(1,pages[0])}</div></div>`; } else {book.innerHTML = `${staticPage('left', prev.pageLeft, prev.left)}${staticPage('right', curr.pageRight, curr.right)}<div class="gutter"></div><div class="turn-page backward" id="turner"><div class="face front">${pageHtml(curr.pageLeft,curr.left)}</div><div class="face back">${pageHtml(prev.pageRight,prev.right)}</div></div>`;} }
 wireQr(); updateControls();}
function startDrag(e){if (turning) return; const dir = e.currentTarget.dataset.dir; if (dir==='next' && spreadIndex>=spreads.length-1) return; if (dir==='prev' && spreadIndex<=0) return; e.preventDefault(); turning = {dir, rect: book.getBoundingClientRect(), progress: 0}; setupTurnScene(dir); window.addEventListener('pointermove', onDrag); window.addEventListener('pointerup', endDrag);}
function onDrag(e){ if (!turning) return; const t=document.getElementById('turner'); const r=turning.rect; let p; if (turning.dir==='next'){ p = 1 - ((e.clientX - r.left) / r.width); } else { p = (e.clientX - r.left) / r.width; } p = Math.max(0, Math.min(1, p)); turning.progress = p; const deg = turning.dir==='next' ? -180 * p : 180 * (1-p); t.style.transform = `rotateY(${deg}deg)`; }
function endDrag(){ if (!turning) return; const commit = turning.progress > .35; const dir = turning.dir; const t = document.getElementById('turner'); t.style.transition = 'transform .45s ease'; const endDeg = dir==='next' ? (commit ? -180 : 0) : (commit ? 0 : 180); t.style.transform = `rotateY(${endDeg}deg)`; window.removeEventListener('pointermove', onDrag); window.removeEventListener('pointerup', endDrag); setTimeout(()=>{ if (commit) spreadIndex += dir==='next' ? 1 : -1; turning = null; render(); }, 460); }
prevBtn.addEventListener('click', ()=>{ if (!turning && spreadIndex>0){ spreadIndex--; render(); }});
nextBtn.addEventListener('click', ()=>{ if (!turning && spreadIndex<spreads.length-1){ spreadIndex++; render(); }});
zoomRange.addEventListener('input', ()=>{ const z = Number(zoomRange.value)/100; stage.style.transform = `scale(${z})`; zoomLabel.textContent = `${zoomRange.value}%`; });
render();